#!/bin/bash

# GitHub repository URL
REPO_URL="https://github.com/Muaaaa849/dv-kemushi-portfolio.git"

echo "================================================"
echo "GitHub Push Helper for DV Kemushi Portfolio"
echo "================================================"
echo ""
echo "このスクリプトは、コードをGitHubにプッシュするのを助けます。"
echo ""
echo "📝 必要なもの："
echo "1. GitHubユーザー名: Muaaaa849"
echo "2. GitHub Personal Access Token (PAT)"
echo ""
echo "🔑 Personal Access Token の作成方法："
echo "1. https://github.com/settings/tokens/new にアクセス"
echo "2. 'repo' スコープを選択"
echo "3. 'Generate token' をクリック"
echo "4. トークンをコピー"
echo ""
echo "準備ができたら、以下のコマンドを実行してください："
echo ""
echo "git push https://YOUR_GITHUB_TOKEN@github.com/Muaaaa849/dv-kemushi-portfolio.git main"
echo ""
echo "例："
echo "git push https://ghp_xxxxxxxxxxxx@github.com/Muaaaa849/dv-kemushi-portfolio.git main"
echo ""
echo "================================================"